### ISSUE TITLE
Error when building package

### ISSUE THREAD

**Issue by teonbrooks** [openexp/OpenEXP#17]
I'm getting build errors when I run `npm run build`

``` node
ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.min.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Applications/packages/OpenEXP/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Applications/packages/OpenEXP/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Applications/packages/OpenEXP/node_modules/css-loader/lib/processCss.js:181:5)
    at Object.module.exports (/Applications/packages/OpenEXP/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/style-loader!./~/css-loader!./~/bootstrap/dist/css/bootstrap.min.css 4:14-77 13:2-17:4 14:20-83
```

also when I run npm start, the app is empty

**Comment by tashoecraft** [comment]
did you npm install before launching?

**Comment by teonbrooks** [comment]
yep, i did.

**Comment by teonbrooks** [comment]
this was resolved with @tashoecraft suggestion that `node` be at least at `v4.0.0`
