### ISSUE TITLE
Readme.md out of date/not working

### ISSUE THREAD

**Issue by andrewjaykeller** [openexp/OpenEXP#19]
Step 5. Deploy

Module does not exist...

```
Error: Cannot find module '/Users/ajk/OpenEXP/server.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by teonbrooks** [comment]
ah, thanks for mentioning this. these steps have changed. I will update the readme soon

**Comment by andrewjaykeller** [comment]
@teonlamont can we close this?
